### ISSUE TITLE
Detectors actions are dispatched recursively and not chronologically.

### ISSUE THREAD

**Issue by etienne-dldc** [piotr-oles/redux-detector#11]
Let say you have a counter
```ts
const initialState = 0
```

and you also have a detector
```ts
const detector = (prevCounter, nextCounter) => {
    // when counter == 1
    if (prevCounter !== nextCounter && nextCounter === 1) {
        return [incrementBy(1), multiplyBy(2)];
    }
    // when counter == 2
    if (prevCounter !== nextCounter && nextCounter === 2) {
        return incrementBy(1);
    }
}
```

Then you dispatch `increment(1)`, what is the value of `state.counter` ?

Answer: it's 6 ! Because the order actions are dispatch is the following:
- The first increment (0 -> 1),
- The first action from detector counter === 1 (1 -> 2)
- The action from detector counter === 2 (2 -> 3)
- The second action from detector counter === 1 (3 -> 6)

I think this is a bit odd and unexpected (earlier actions should be dispatched first).
Expected answer would be 5 (increment, increment, multiply, increment).

**Comment by piotr-oles** [comment]
Released as 0.8.0 :)
